export type TexasOemEbayTemplateInput={title?:string|null;partName?:string|null;partNumber?:string|null;interchangeNumber?:string|null;sku?:string|null;condition?:string|null;notes?:string|null;year?:string|null;make?:string|null;model?:string|null;trim?:string|null;mileage?:string|number|null;position?:string|null;category?:string|null;shippingText?:string|null;warrantyText?:string|null;primaryPhotoUrl?:string|null;photoUrls?:Array<string|null|undefined>}
const esc=(v:unknown)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')
const val=(v:unknown,f='—')=>esc(String(v??'').trim()||f)
export function buildTexasOemEbayDescription(i:TexasOemEbayTemplateInput){
 const name=String(i.partName??'OEM Auto Part').trim()||'OEM Auto Part';let title=String(i.title??name).trim()||name;title=title.replace(/\s+for\s+vehicle\s*$/i,'').trim()||name
 const pn=String(i.partNumber??'').trim(),condition=String(i.condition??'Used').trim()||'Used',notes=String(i.notes??'').trim()||'Condition and fitment should be verified before sale.'
 const photos=[i.primaryPhotoUrl,...(i.photoUrls??[])].map(x=>String(x??'').trim()).filter(Boolean).filter((x,n,a)=>a.indexOf(x)===n).slice(0,6),hero=photos[0],thumbs=photos.slice(0,5)
 const row=(icon:string,label:string,value:unknown,bold=false)=>`<tr><td style="width:36px;padding:9px 4px;border-top:1px solid #dbe1e6;text-align:center;color:#062b53;font-weight:900">${icon}</td><td style="width:105px;padding:9px 7px;border-top:1px solid #dbe1e6;font-size:11px;font-weight:800;color:#17283a">${label}</td><td style="padding:9px 8px;border-top:1px solid #dbe1e6;font-size:11px;color:#263b50;${bold?'font-weight:900;color:#062b53':''};word-break:break-word">${val(value)}</td></tr>`
 const rows=row('⚙','Condition:',condition)+row('◎','OEM Part #:',pn||'—',true)+row('✣','Interchange:',i.interchangeNumber)+row('§','SKU:',i.sku)+row('▣','Category:',i.category||'General OEM Parts')+row('✎','Notes:',notes)+row('⊙','VIN:','—')
 const thumbHtml=thumbs.map((u,n)=>`<span style="display:inline-block;width:78px;height:52px;margin:0 5px;padding:3px;border:${n===0?'2px solid #062b53':'1px solid #d9dee3'};border-radius:9px;background:#fff;box-sizing:border-box;vertical-align:top"><img src="${esc(u)}" style="width:100%;height:100%;object-fit:cover;border-radius:5px;display:block"></span>`).join('')
 return `<div style="margin:0;background:#fff;font-family:Arial,Helvetica,sans-serif;color:#17283a"><div style="max-width:1500px;margin:0 auto;background:#fff;overflow:hidden">
 <div style="background:#031f40;color:#fff;padding:12px 26px 14px;border-bottom:1px solid rgba(255,255,255,.45)"><div style="font-size:18px;font-weight:900">Texas OEM Parts</div><div style="font-size:12px;margin-top:5px;color:#eef3f7">eBay listing preview — nothing is being published</div></div>
 <div style="background:#031f40;color:#fff;padding:12px 76px 27px"><table style="width:100%;border-collapse:collapse"><tr><td style="width:115px"><div style="width:82px;height:70px;line-height:70px;text-align:center;font-size:25px;font-weight:900;border:2px solid #fff;border-radius:4px 28px 7px 26px">TX</div></td><td><div style="font-size:30px;font-weight:900;letter-spacing:.2px">TEXAS OEM PARTS</div><div style="font-size:12px;margin-top:6px;letter-spacing:.5px">GENUINE OEM AUTO PARTS</div></td><td style="text-align:right;white-space:nowrap"><span style="display:inline-block;margin-left:30px;font-size:11px;font-weight:800">◯&nbsp; TESTED &amp;<br>&nbsp;&nbsp;&nbsp;&nbsp;INSPECTED</span><span style="display:inline-block;margin-left:36px;font-size:11px;font-weight:800">✪&nbsp; PROFESSIONAL<br>&nbsp;&nbsp;&nbsp;&nbsp;SERVICE</span><span style="display:inline-block;margin-left:36px;font-size:11px;font-weight:800">▱&nbsp; FAST<br>&nbsp;&nbsp;&nbsp;&nbsp;SHIPPING</span></td></tr></table></div>
 <div style="height:22px;background:#031f40;border-radius:0 0 50% 50%/0 0 100% 100%;margin-top:-1px"></div>
 <div style="height:39px;line-height:39px;text-align:center;background:#f6f6f6;color:#203a55;font-size:11px;font-weight:800">• &nbsp; GENUINE OEM PARTS &nbsp; • &nbsp; TESTED &amp; INSPECTED &nbsp; • &nbsp; FAST SHIPPING &nbsp; • &nbsp; BUY WITH CONFIDENCE</div>
 <div style="padding:18px 110px 12px"><table style="width:100%;border-collapse:collapse"><tr><td><div style="font-size:11px;font-weight:900;color:#7b858e">READY TO SHIP</div><div style="font-size:29px;font-weight:900;color:#062b53;margin-top:5px">${val(title)}</div><div style="font-size:11px;color:#697681;margin-top:7px">${val(condition)} condition &nbsp; • &nbsp; Professionally inspected &nbsp; • &nbsp; Buy with confidence</div></td>${pn?`<td style="width:280px;text-align:right"><div style="display:inline-block;width:245px;border:1px solid #d0d6dc;border-radius:8px;overflow:hidden;box-shadow:0 3px 10px rgba(0,0,0,.12);text-align:center"><div style="background:#031f40;color:#fff;padding:6px;font-size:10px;font-weight:900">OEM PART NUMBER</div><div style="padding:10px;background:#fff;font-size:22px;font-weight:900;color:#062b53">${val(pn)}</div></div></td>`:''}</tr></table></div>
 <div style="padding:5px 110px 18px"><table style="width:100%;border-collapse:separate;border-spacing:22px 0;margin:0 -22px;width:calc(100% + 44px)"><tr><td style="width:56%;vertical-align:top"><div style="height:380px;border:1px solid #d6dce1;border-radius:13px;padding:14px 18px;background:#fff;box-sizing:border-box;position:relative;text-align:center">${hero?`<img src="${esc(hero)}" style="display:block;width:100%;height:280px;object-fit:contain;margin:0 auto;border-radius:7px">`:''}<div style="position:absolute;left:10px;top:42%;width:28px;height:28px;line-height:27px;border:1px solid #d8dde2;border-radius:50%;background:#fff;color:#062b53;font-size:20px">‹</div><div style="position:absolute;right:10px;top:42%;width:28px;height:28px;line-height:27px;border:1px solid #d8dde2;border-radius:50%;background:#fff;color:#062b53;font-size:20px">›</div><div style="margin-top:12px;white-space:nowrap">${thumbHtml}<span style="display:inline-block;width:78px;height:52px;line-height:52px;border:1px solid #d9dee3;border-radius:9px;font-size:9px;font-weight:900;color:#062b53;vertical-align:top">TX OEM</span></div></div></td><td style="width:44%;vertical-align:top"><div style="height:380px;border:1px solid #d6dce1;border-radius:13px;padding:12px 18px;background:#fff;box-sizing:border-box;box-shadow:0 3px 10px rgba(0,0,0,.05);overflow:hidden"><div style="font-size:12px;font-weight:900;color:#111;margin-bottom:5px">ITEM DETAILS</div><table style="width:100%;border-collapse:collapse">${rows}</table></div></td></tr></table></div>
 <div style="padding:0 110px 17px"><table style="width:100%;border-collapse:separate;border-spacing:22px 0;margin:0 -22px;width:calc(100% + 44px)"><tr><td style="width:50%"><div style="height:110px;border:1px solid #d6dce1;border-radius:12px;overflow:hidden;display:table;width:100%;box-sizing:border-box"><div style="display:table-cell;width:72px;background:#031f40;color:#fff;text-align:center;vertical-align:middle;font-size:30px">◇</div><div style="display:table-cell;padding:10px 16px;vertical-align:middle"><div style="font-size:12px;font-weight:900;color:#111;margin-bottom:7px">WHY BUY FROM US?</div><div style="font-size:10px;line-height:1.8">✓ Genuine OEM inventory &nbsp;&nbsp;&nbsp;&nbsp; ✓ Fast professional shipping<br>✓ Tested and inspected &nbsp;&nbsp;&nbsp;&nbsp; ✓ Responsive customer service<br>✓ Carefully packaged</div></div></div></td><td style="width:50%"><div style="height:110px;border:1px solid #d6dce1;border-radius:12px;overflow:hidden;display:table;width:100%;box-sizing:border-box"><div style="display:table-cell;width:72px;background:#031f40;color:#fff;text-align:center;vertical-align:middle;font-size:29px">◉</div><div style="display:table-cell;padding:10px 16px;vertical-align:middle"><div style="font-size:12px;font-weight:900;color:#111;margin-bottom:7px">NOTE TO BUYER</div><div style="font-size:10px;line-height:1.7">Please match the OEM part number and verify fitment before purchasing.<br>If you are unsure, message us before ordering and we will be happy to help.</div></div></div></td></tr></table></div>
 <div style="background:#031f40;color:#fff;padding:17px 85px 22px"><table style="width:100%;border-collapse:collapse"><tr><td style="width:85px"><div style="font-size:22px;font-weight:900">TX</div></td><td><div style="font-size:20px;font-weight:900">TEXAS OEM PARTS</div><div style="font-size:9px;margin-top:5px">GENUINE OEM &nbsp; • &nbsp; TESTED &nbsp; • &nbsp; PROFESSIONAL SERVICE &nbsp; • &nbsp; FAST SHIPPING</div><div style="font-size:9px;margin-top:7px">Thank you for supporting Texas OEM Parts.</div></td><td style="text-align:right;font-size:10px">PROUDLY SERVING CUSTOMERS<br><br>ACROSS THE UNITED STATES</td></tr></table></div>
 </div></div>`.trim()
}