export type TexasOemEbayTemplateInput = {
  title?: string | null; partName?: string | null; partNumber?: string | null; interchangeNumber?: string | null; sku?: string | null; condition?: string | null; notes?: string | null; year?: string | null; make?: string | null; model?: string | null; trim?: string | null; mileage?: string | number | null; position?: string | null; category?: string | null; shippingText?: string | null; warrantyText?: string | null; primaryPhotoUrl?: string | null; photoUrls?: Array<string | null | undefined>
}
function escapeHtml(value: unknown) { return String(value ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;') }
function text(value: unknown, fallback='N/A') { const v=String(value ?? '').trim(); return escapeHtml(v || fallback) }
function useful(value: unknown) { const v=String(value ?? '').trim().toLowerCase(); return Boolean(v) && !['n/a','na','donor unavailable','vehicle','for vehicle'].includes(v) }
function cleanTitle(input: TexasOemEbayTemplateInput, showVehicle:boolean) { const p=String(input.partName ?? 'OEM Auto Part').trim() || 'OEM Auto Part'; let t=String(input.title ?? '').trim(); if(!showVehicle)t=t.replace(/\s+for\s+vehicle\s*$/i,'').replace(/\s+for\s+donor unavailable\s*$/i,'').trim(); return !t || /^for vehicle$/i.test(t) ? p : t }
export function buildTexasOemEbayDescription(input: TexasOemEbayTemplateInput) {
 const showVehicle=[input.year,input.make,input.model,input.trim].some(useful); const vehicle=[input.year,input.make,input.model,input.trim].map(v=>String(v??'').trim()).filter(useful).join(' '); const partName=String(input.partName??'OEM Auto Part').trim()||'OEM Auto Part'; const title=cleanTitle(input,showVehicle); const condition=String(input.condition??'Used OEM').trim()||'Used OEM'; const shipping=String(input.shippingText??'FREE SHIPPING — Lower 48 States').trim(); const warranty=String(input.warrantyText??'30 Day Warranty').trim(); const notes=String(input.notes??'').trim()||'Please review all photos and verify part number and fitment before purchase.'; const pn=String(input.partNumber??'').trim();
 const photos=[input.primaryPhotoUrl,...(input.photoUrls??[])].map(v=>String(v??'').trim()).filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).slice(0,7); const hero=photos[0]; const secondary=photos.slice(1);
 const photoHtml=hero?`<div style="background:#fafafa;border:1px solid #d7dce1;padding:14px;margin-bottom:12px;text-align:center;"><img src="${escapeHtml(hero)}" alt="${escapeHtml(partName)}" style="display:block;max-width:100%;width:auto;height:auto;max-height:485px;margin:0 auto;object-fit:contain;"/></div>${secondary.length?`<div style="text-align:center;margin:0 -3px 20px;">${secondary.map((u,i)=>`<img src="${escapeHtml(u)}" alt="${escapeHtml(`${partName} photo ${i+2}`)}" style="display:inline-block;width:29%;max-width:230px;height:125px;object-fit:cover;margin:3px;border:1px solid #d7dce1;background:#fff;vertical-align:top;"/>`).join('')}</div>`:''}`:'';
 const section=(name:string)=>`<div style="background:#163b5c;color:#fff;padding:11px 14px;font-size:15px;font-weight:800;letter-spacing:.3px;">${name}</div>`;
 const vehicleHtml=showVehicle?`<td style="width:50%;vertical-align:top;padding-left:9px;">${section('VEHICLE / FITMENT')}<table cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;border:1px solid #d7dce1;border-top:0;"><tr><td style="padding:10px 12px;font-weight:700;border-bottom:1px solid #e3e6e9;width:38%;">DONOR</td><td style="padding:10px 12px;border-bottom:1px solid #e3e6e9;">${text(vehicle)}</td></tr><tr><td style="padding:10px 12px;font-weight:700;border-bottom:1px solid #e3e6e9;">POSITION</td><td style="padding:10px 12px;border-bottom:1px solid #e3e6e9;">${text(input.position,'—')}</td></tr><tr><td style="padding:10px 12px;font-weight:700;">MILEAGE</td><td style="padding:10px 12px;">${text(input.mileage,'—')}</td></tr></table></td>`:'';
 return `<div style="margin:0;padding:0;background:#f1f2f3;font-family:Arial,Helvetica,sans-serif;color:#27323b;"><div style="max-width:980px;margin:0 auto;background:#fff;border:1px solid #d7dce1;">
 <div style="background:#163b5c;padding:21px 28px;border-bottom:5px solid #9aa4ad;"><table cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;"><tr><td><div style="font-size:30px;font-weight:800;color:#fff;letter-spacing:-1px;">TEXAS OEM PARTS</div><div style="margin-top:6px;font-size:11px;letter-spacing:2px;color:#d8dde1;">GENUINE OEM AUTO PARTS</div></td><td style="text-align:right;color:#d8dde1;font-size:11px;line-height:1.7;font-weight:700;">TESTED &amp; INSPECTED<br/>PROFESSIONAL SERVICE • FAST SHIPPING</td></tr></table></div>
 <div style="padding:25px 28px 20px;background:#fff;"><table cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;"><tr><td style="padding-right:18px;"><div style="font-size:11px;font-weight:800;letter-spacing:1.5px;color:#6d7881;margin-bottom:7px;">${showVehicle?'OEM REPLACEMENT PART':'READY TO SHIP'}</div><div style="font-size:27px;line-height:1.2;font-weight:800;color:#183247;">${text(title)}</div><div style="margin-top:9px;font-size:12px;color:#6d7881;">${text(condition)} • Professionally inspected • Buy with confidence</div></td>${pn?`<td style="width:220px;text-align:right;"><div style="display:inline-block;min-width:185px;background:#f4f5f6;border:1px solid #c8cdd2;text-align:center;"><div style="padding:7px 10px;color:#626d76;font-size:10px;font-weight:800;letter-spacing:1.1px;">OEM PART NUMBER</div><div style="padding:10px 12px;background:#e4e7e9;color:#163b5c;font-size:21px;font-weight:900;">${text(pn)}</div></div></td>`:''}</tr></table></div>
 <div style="background:#f0f1f2;border-top:1px solid #d7dce1;border-bottom:1px solid #d7dce1;color:#4d5962;padding:9px 28px;font-size:11px;font-weight:800;letter-spacing:.8px;text-align:center;">GENUINE OEM • TESTED &amp; INSPECTED • FAST SHIPPING • BUY WITH CONFIDENCE</div>
 <div style="padding:18px 28px 0;">${photoHtml}<table cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;margin-bottom:22px;"><tr><td style="width:${showVehicle?'50%':'100%'};vertical-align:top;${showVehicle?'padding-right:9px;':''}">${section('ITEM DETAILS')}<table cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;border:1px solid #d7dce1;border-top:0;"><tr><td style="padding:10px 12px;font-weight:700;border-bottom:1px solid #e3e6e9;width:38%;">PART NAME</td><td style="padding:10px 12px;border-bottom:1px solid #e3e6e9;">${text(partName)}</td></tr>${pn?`<tr><td style="padding:10px 12px;font-weight:700;border-bottom:1px solid #e3e6e9;">OEM PART #</td><td style="padding:10px 12px;border-bottom:1px solid #e3e6e9;color:#163b5c;font-weight:900;">${text(pn)}</td></tr>`:''}<tr><td style="padding:10px 12px;font-weight:700;border-bottom:1px solid #e3e6e9;">INTERCHANGE</td><td style="padding:10px 12px;border-bottom:1px solid #e3e6e9;">${text(input.interchangeNumber,'—')}</td></tr><tr><td style="padding:10px 12px;font-weight:700;border-bottom:1px solid #e3e6e9;">CONDITION</td><td style="padding:10px 12px;border-bottom:1px solid #e3e6e9;">${text(condition)}</td></tr><tr><td style="padding:10px 12px;font-weight:700;border-bottom:1px solid #e3e6e9;">SKU</td><td style="padding:10px 12px;border-bottom:1px solid #e3e6e9;">${text(input.sku)}</td></tr><tr><td style="padding:10px 12px;font-weight:700;">CATEGORY</td><td style="padding:10px 12px;">${text(input.category,'General OEM Parts')}</td></tr></table></td>${vehicleHtml}</tr></table>
 <div style="border:1px solid #d7dce1;margin-bottom:22px;">${section('ITEM DESCRIPTION')}<div style="font-size:14px;line-height:1.7;color:#3f4a52;padding:17px 18px 19px;">${text(notes)}</div></div>
 <table cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;margin-bottom:22px;"><tr>${[['✓','OEM QUALITY','Inspected part'],['◆','PART VERIFIED','Details checked'],['→','FAST SHIPPING',shipping],['★',warranty,'Buy with confidence']].map(x=>`<td style="width:25%;padding:15px 8px;text-align:center;border:1px solid #d7dce1;background:#fafafa;"><div style="font-size:19px;color:#7a858e;">${x[0]}</div><div style="font-size:12px;font-weight:800;color:#183247;margin-top:6px;">${text(x[1])}</div><div style="font-size:10px;color:#737d85;margin-top:3px;">${text(x[2])}</div></td>`).join('')}</tr></table>
 <table cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;margin-bottom:22px;"><tr><td style="width:50%;vertical-align:top;padding-right:9px;">${section('WHY BUY FROM US?')}<div style="border:1px solid #d7dce1;border-top:0;padding:15px 18px;font-size:12px;line-height:1.85;color:#465159;">✓ Genuine OEM inventory<br/>✓ Tested and inspected<br/>✓ Carefully packaged<br/>✓ Fast professional shipping<br/>✓ Responsive customer service</div></td><td style="width:50%;vertical-align:top;padding-left:9px;"><div style="background:#6f7a83;color:#fff;padding:11px 14px;font-size:14px;font-weight:800;">NOTE TO BUYER</div><div style="border:1px solid #d7dce1;border-top:0;padding:15px 18px;font-size:12px;line-height:1.7;color:#465159;min-height:116px;">Please match the OEM part number and verify fitment before purchasing. If you are unsure, message us before ordering and we will be happy to help.</div></td></tr></table></div>
 <div style="background:#163b5c;border-top:5px solid #9aa4ad;padding:20px 28px;color:#fff;"><table cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;"><tr><td><div style="font-size:21px;font-weight:800;">TEXAS OEM PARTS</div><div style="margin-top:6px;font-size:10px;letter-spacing:1px;color:#d8dde1;">GENUINE OEM • TESTED • PROFESSIONAL SERVICE • FAST SHIPPING</div></td><td style="text-align:right;font-size:11px;color:#d8dde1;">Thank you for supporting Texas OEM Parts.</td></tr></table></div>
 </div></div>`.trim()
}