export type TexasOemEbayTemplateInput = { title?: string|null; partName?: string|null; partNumber?: string|null; interchangeNumber?: string|null; sku?: string|null; condition?: string|null; notes?: string|null; year?: string|null; make?: string|null; model?: string|null; trim?: string|null; mileage?: string|number|null; position?: string|null; category?: string|null; shippingText?: string|null; warrantyText?: string|null; primaryPhotoUrl?: string|null; photoUrls?: Array<string|null|undefined> }
const esc=(v:unknown)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')
const val=(v:unknown,f='—')=>esc(String(v??'').trim()||f)
const useful=(v:unknown)=>{const s=String(v??'').trim().toLowerCase();return !!s&&!['n/a','na','donor unavailable','vehicle','for vehicle'].includes(s)}
export function buildTexasOemEbayDescription(i:TexasOemEbayTemplateInput){
 const showVehicle=[i.year,i.make,i.model,i.trim].some(useful)
 const vehicle=[i.year,i.make,i.model,i.trim].filter(useful).join(' ')
 const name=String(i.partName??'OEM Auto Part').trim()||'OEM Auto Part'
 let title=String(i.title??name).trim()||name
 if(!showVehicle) title=title.replace(/\s+for\s+vehicle\s*$/i,'').replace(/\s+for\s+donor unavailable\s*$/i,'').trim()||name
 const pn=String(i.partNumber??'').trim(); const condition=String(i.condition??'Used OEM').trim()||'Used OEM'; const notes=String(i.notes??'').trim()||'Condition and fitment should be verified before sale.'
 const photos=[i.primaryPhotoUrl,...(i.photoUrls??[])].map(x=>String(x??'').trim()).filter(Boolean).filter((x,n,a)=>a.indexOf(x)===n).slice(0,6); const hero=photos[0]; const thumbs=photos.slice(0,5)
 const rows=[['◉','Condition:',condition],['◎','OEM Part #:',pn||'—'],['↕','Interchange:',String(i.interchangeNumber??'').trim()||'—'],['§','SKU:',String(i.sku??'').trim()||'—'],['▣','Category:',String(i.category??'').trim()||'General OEM Parts'],['✎','Notes:',notes],...(showVehicle?[['⌖','VIN / Donor:',vehicle]]:[['⊙','VIN:','—']])].map((r,idx,arr)=>`<tr><td style="width:34px;padding:11px 5px;border-bottom:${idx===arr.length-1?'0':'1px solid #dce2e7'};color:#092d53;font-weight:900;font-size:16px;text-align:center;vertical-align:top">${r[0]}</td><td style="width:118px;padding:11px 8px;border-bottom:${idx===arr.length-1?'0':'1px solid #dce2e7'};font-size:12px;font-weight:800;color:#182b3d;vertical-align:top">${r[1]}</td><td style="padding:11px 8px;border-bottom:${idx===arr.length-1?'0':'1px solid #dce2e7'};font-size:12px;color:#2b4054;vertical-align:top;word-break:break-word;${r[1]==='OEM Part #:'?'font-weight:900;color:#092d53;':''}">${val(r[2])}</td></tr>`).join('')
 const thumbHtml=thumbs.map((u,n)=>`<span style="display:inline-block;width:86px;height:58px;margin:4px 5px;padding:4px;background:#fff;border:${n===0?'2px solid #092d53':'1px solid #d5dce2'};border-radius:10px;box-sizing:border-box;vertical-align:top;box-shadow:${n===0?'0 2px 7px rgba(9,45,83,.13)':'none'}"><img src="${esc(u)}" style="display:block;width:100%;height:100%;object-fit:cover;border-radius:6px"/></span>`).join('')
 return `<div style="margin:0;background:#f4f5f6;font-family:Arial,Helvetica,sans-serif;color:#1c2d3f"><div style="max-width:1160px;margin:0 auto;background:#fff;overflow:hidden;box-shadow:0 8px 30px rgba(9,35,61,.10)">
 <div style="background:#06284c;color:#fff;padding:28px 38px 34px;position:relative"><table style="width:100%;border-collapse:collapse"><tr><td style="width:96px;vertical-align:middle"><div style="width:72px;height:58px;border:2px solid #fff;border-radius:30px 10px 28px 7px;line-height:58px;text-align:center;font-size:25px;font-weight:900">TX</div></td><td style="vertical-align:middle"><div style="font-size:32px;font-weight:900;letter-spacing:.3px">TEXAS OEM PARTS</div><div style="margin-top:5px;font-size:11px;letter-spacing:1.8px;color:#e5ebf1">GENUINE OEM AUTO PARTS</div></td><td style="text-align:right;vertical-align:middle"><span style="display:inline-block;margin-left:24px;font-size:11px;font-weight:800;line-height:1.45">⬡ TESTED &amp;<br/>INSPECTED</span><span style="display:inline-block;margin-left:30px;font-size:11px;font-weight:800;line-height:1.45">★ PROFESSIONAL<br/>SERVICE</span><span style="display:inline-block;margin-left:30px;font-size:11px;font-weight:800;line-height:1.45">▱ FAST<br/>SHIPPING</span></td></tr></table></div>
 <div style="height:19px;background:#06284c;border-radius:0 0 50% 50%/0 0 100% 100%;margin-top:-1px"></div>
 <div style="text-align:center;padding:12px 20px;background:#f7f7f7;color:#24415e;font-size:11px;font-weight:800;letter-spacing:.45px">GENUINE OEM PARTS &nbsp; • &nbsp; TESTED &amp; INSPECTED &nbsp; • &nbsp; FAST SHIPPING &nbsp; • &nbsp; BUY WITH CONFIDENCE</div>
 <div style="padding:24px 36px 12px"><table style="width:100%;border-collapse:collapse"><tr><td><div style="font-size:11px;font-weight:900;color:#7a858e;letter-spacing:1px">${showVehicle?'OEM REPLACEMENT PART':'READY TO SHIP'}</div><div style="font-size:31px;font-weight:900;color:#08294e;margin-top:6px">${val(title)}</div><div style="font-size:12px;color:#697783;margin-top:8px">${val(condition)} &nbsp; • &nbsp; Professionally inspected &nbsp; • &nbsp; Buy with confidence</div></td>${pn?`<td style="width:245px;text-align:right"><div style="display:inline-block;width:220px;border:1px solid #ccd4db;border-radius:10px;overflow:hidden;box-shadow:0 4px 12px rgba(11,42,73,.12);text-align:center"><div style="background:#08294e;color:#fff;padding:7px 10px;font-size:10px;font-weight:900">OEM PART NUMBER</div><div style="background:#fff;padding:13px 10px;font-size:23px;font-weight:900;color:#08294e">${val(pn)}</div></div></td>`:''}</tr></table></div>
 <div style="padding:8px 36px 16px"><table style="width:100%;border-collapse:separate;border-spacing:18px 0;margin:0 -18px;width:calc(100% + 36px)"><tr><td style="width:58%;vertical-align:top"><div style="position:relative;border:1px solid #d3dae0;border-radius:15px;padding:16px;background:#fff;box-shadow:0 4px 14px rgba(20,40,60,.06);text-align:center">${hero?`<img src="${esc(hero)}" alt="${esc(name)}" style="display:block;width:100%;height:360px;object-fit:contain;margin:auto;border-radius:10px"/>`:''}<div style="position:absolute;left:10px;top:45%;width:28px;height:28px;border:1px solid #d4dbe1;border-radius:50%;background:#fff;line-height:26px;color:#08294e;font-size:21px;font-weight:900;box-shadow:0 2px 7px rgba(0,0,0,.08)">‹</div><div style="position:absolute;right:10px;top:45%;width:28px;height:28px;border:1px solid #d4dbe1;border-radius:50%;background:#fff;line-height:26px;color:#08294e;font-size:21px;font-weight:900;box-shadow:0 2px 7px rgba(0,0,0,.08)">›</div><div style="margin-top:12px">${thumbHtml}<span style="display:inline-block;width:86px;height:58px;margin:4px 5px;border:1px solid #d5dce2;border-radius:10px;background:#fff;vertical-align:top;box-sizing:border-box;line-height:58px;color:#08294e;font-size:10px;font-weight:900">TX OEM</span></div></div></td><td style="width:42%;vertical-align:top"><div style="border:1px solid #d3dae0;border-radius:15px;padding:15px 18px 10px;background:#fff;box-shadow:0 4px 14px rgba(20,40,60,.06)"><div style="font-size:13px;font-weight:900;color:#111;margin-bottom:8px">ITEM DETAILS</div><table style="width:100%;border-collapse:collapse">${rows}</table></div></td></tr></table></div>
 <div style="padding:0 36px 16px"><table style="width:100%;border-collapse:separate;border-spacing:18px 0;margin:0 -18px;width:calc(100% + 36px)"><tr><td style="width:50%;vertical-align:top"><div style="display:table;width:100%;border:1px solid #d3dae0;border-radius:14px;overflow:hidden;box-shadow:0 3px 10px rgba(20,40,60,.05)"><div style="display:table-cell;width:72px;background:#08294e;color:#fff;text-align:center;vertical-align:middle;font-size:30px;font-weight:900">◈</div><div style="display:table-cell;padding:14px 16px;background:#fff;vertical-align:middle"><div style="font-size:12px;font-weight:900;color:#17293b;margin-bottom:7px">WHY BUY FROM US?</div><div style="font-size:11px;line-height:1.9;color:#445562">✓ Genuine OEM inventory &nbsp;&nbsp; ✓ Fast professional shipping<br/>✓ Tested and inspected &nbsp;&nbsp; ✓ Responsive customer service<br/>✓ Carefully packaged</div></div></div></td><td style="width:50%;vertical-align:top"><div style="display:table;width:100%;border:1px solid #d3dae0;border-radius:14px;overflow:hidden;box-shadow:0 3px 10px rgba(20,40,60,.05)"><div style="display:table-cell;width:72px;background:#08294e;color:#fff;text-align:center;vertical-align:middle;font-size:28px;font-weight:900">◌</div><div style="display:table-cell;padding:14px 16px;background:#fff;vertical-align:middle"><div style="font-size:12px;font-weight:900;color:#17293b;margin-bottom:7px">NOTE TO BUYER</div><div style="font-size:11px;line-height:1.75;color:#445562">Please match the OEM part number and verify fitment before purchasing. If you are unsure, message us before ordering and we will be happy to help.</div></div></div></td></tr></table></div>
 <div style="height:19px;background:#06284c;border-radius:50% 50% 0 0/100% 100% 0 0"></div><div style="background:#06284c;color:#fff;padding:17px 38px 23px"><table style="width:100%;border-collapse:collapse"><tr><td style="width:84px"><div style="width:58px;height:48px;border:2px solid #fff;border-radius:24px 8px 22px 6px;line-height:48px;text-align:center;font-weight:900">TX</div></td><td><div style="font-size:20px;font-weight:900">TEXAS OEM PARTS</div><div style="margin-top:5px;font-size:9px;letter-spacing:1px;color:#dfe6ec">GENUINE OEM • TESTED • PROFESSIONAL SERVICE • FAST SHIPPING</div></td><td style="text-align:right;font-size:10px;color:#dfe6ec">PROUDLY SERVING CUSTOMERS<br/>ACROSS THE UNITED STATES</td></tr></table></div>
 </div></div>`.trim()
}