create table if not exists public.vehicle_configurations (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid references public.vehicles(id) on delete cascade,
  vin text,
  year integer,
  make text,
  model text,
  trim text,
  body_class text,
  drive_type text,
  engine_displacement text,
  engine_cylinders text,
  fuel_type text,
  transmission_style text,
  raw_decode jsonb,
  created_at timestamptz default now()
);

create table if not exists public.vehicle_part_templates (
  id uuid primary key default gen_random_uuid(),
  year_from integer,
  year_to integer,
  make text,
  model text,
  trim text,
  engine text,
  drive_type text,
  body_class text,
  part_master_id uuid references public.part_master(id) on delete cascade,
  default_selected boolean default true,
  priority integer default 100,
  notes text,
  created_at timestamptz default now()
);

alter table public.part_master add column if not exists side text;
alter table public.part_master add column if not exists position text;
alter table public.part_master add column if not exists default_pull_priority integer;
alter table public.part_master add column if not exists typical_weight numeric;
alter table public.part_master add column if not exists requires_testing boolean default false;
alter table public.part_master add column if not exists normally_shipped boolean default true;
alter table public.part_master add column if not exists active boolean default true;

insert into public.part_master (part_code, part_name, category, side, position, default_pull_priority, typical_weight, requires_testing, normally_shipped, active)
values
  ('ENG', 'Engine', 'Powertrain', null, 'Front', 10, 450, true, true, true),
  ('TRN', 'Transmission', 'Powertrain', null, 'Front', 11, 180, true, true, true),
  ('TCASE', 'Transfer Case', 'Powertrain', null, 'Front', 12, 90, true, true, true),
  ('FDIFF', 'Front Differential', 'Powertrain', null, 'Front', 13, 70, true, true, true),
  ('RDIFF', 'Rear Differential', 'Powertrain', null, 'Rear', 14, 70, true, true, true),
  ('DSHAFT', 'Driveshaft', 'Powertrain', null, 'Rear', 15, 45, true, true, true),
  ('AXLE', 'Axle Assembly', 'Powertrain', null, 'Rear', 16, 80, true, true, true),
  ('ALT', 'Alternator', 'Engine Accessories', null, 'Front', 20, 18, false, true, true),
  ('STRTR', 'Starter', 'Engine Accessories', null, 'Front', 21, 12, false, true, true),
  ('ACCOMP', 'AC Compressor', 'Engine Accessories', null, 'Front', 22, 15, false, true, true),
  ('PSPUMP', 'Power Steering Pump', 'Engine Accessories', null, 'Front', 23, 10, false, true, true),
  ('TURBO', 'Turbocharger', 'Engine Accessories', null, 'Front', 24, 8, false, true, true),
  ('SC', 'Supercharger', 'Engine Accessories', null, 'Front', 25, 9, false, true, true),
  ('INTMAN', 'Intake Manifold', 'Engine Accessories', null, 'Front', 26, 12, false, true, true),
  ('THROTT', 'Throttle Body', 'Engine Accessories', null, 'Front', 27, 4, false, true, true),
  ('FUELINJ', 'Fuel Injectors', 'Engine Accessories', null, 'Front', 28, 3, false, true, true),
  ('IGNCOIL', 'Ignition Coils', 'Engine Accessories', null, 'Front', 29, 2, false, true, true),
  ('ENGHW', 'Engine Wiring Harness', 'Engine Accessories', null, 'Front', 30, 8, false, true, true),
  ('ECM', 'ECM/PCM', 'Engine Accessories', null, 'Front', 31, 4, false, true, true),
  ('FUSEBOX', 'Fuse Box', 'Engine Accessories', null, 'Front', 32, 6, false, true, true),
  ('RADIAT', 'Radiator', 'Engine Accessories', null, 'Front', 33, 20, false, true, true),
  ('COOLFAN', 'Cooling Fan Assembly', 'Engine Accessories', null, 'Front', 34, 12, false, true, true),
  ('IC', 'Intercooler', 'Engine Accessories', null, 'Front', 35, 12, false, true, true),
  ('HOOD', 'Hood', 'Body', null, 'Front', 40, 35, false, true, true),
  ('FRBUMP', 'Front Bumper', 'Body', null, 'Front', 41, 28, false, true, true),
  ('REBUMP', 'Rear Bumper', 'Body', null, 'Rear', 42, 28, false, true, true),
  ('GRILLE', 'Grille', 'Body', null, 'Front', 43, 10, false, true, true),
  ('FDRLF', 'Fender LF', 'Body', 'LF', 'Front', 44, 15, false, true, true),
  ('FDRRF', 'Fender RF', 'Body', 'RF', 'Front', 45, 15, false, true, true),
  ('DRLF', 'Door LF', 'Body', 'LF', 'Front', 46, 20, false, true, true),
  ('DRRF', 'Door RF', 'Body', 'RF', 'Front', 47, 20, false, true, true),
  ('DRLR', 'Door LR', 'Body', 'LR', 'Rear', 48, 20, false, true, true),
  ('DRRR', 'Door RR', 'Body', 'RR', 'Rear', 49, 20, false, true, true),
  ('TAILG', 'Tailgate', 'Body', null, 'Rear', 50, 35, false, true, true),
  ('TRUCKBED', 'Truck Bed', 'Body', null, 'Rear', 51, 90, false, true, true),
  ('MIRLF', 'Mirror LF', 'Body', 'LF', 'Front', 52, 8, false, true, true),
  ('MIRRF', 'Mirror RF', 'Body', 'RF', 'Front', 53, 8, false, true, true),
  ('HLLF', 'Headlight LF', 'Lighting', 'LF', 'Front', 60, 8, false, true, true),
  ('HLRF', 'Headlight RF', 'Lighting', 'RF', 'Front', 61, 8, false, true, true),
  ('TLLF', 'Taillight LF', 'Lighting', 'LF', 'Rear', 62, 5, false, true, true),
  ('TLRF', 'Taillight RF', 'Lighting', 'RF', 'Rear', 63, 5, false, true, true),
  ('FGLF', 'Fog Light LF', 'Lighting', 'LF', 'Front', 64, 4, false, true, true),
  ('FGRF', 'Fog Light RF', 'Lighting', 'RF', 'Front', 65, 4, false, true, true),
  ('TBL', 'Third Brake Light', 'Lighting', null, 'Rear', 66, 3, false, true, true),
  ('RADIO', 'Radio', 'Interior/Electronics', null, 'Front', 70, 4, false, true, true),
  ('DSPLY', 'Display Screen', 'Interior/Electronics', null, 'Front', 71, 3, false, true, true),
  ('CLUSTER', 'Instrument Cluster', 'Interior/Electronics', null, 'Front', 72, 3, false, true, true),
  ('HVAC', 'HVAC Control', 'Interior/Electronics', null, 'Front', 73, 2, false, true, true),
  ('BCM', 'Body Control Module', 'Interior/Electronics', null, 'Front', 74, 2, false, true, true),
  ('AMP', 'Amplifier', 'Interior/Electronics', null, 'Front', 75, 2, false, true, true),
  ('STRCOL', 'Steering Column', 'Interior/Electronics', null, 'Front', 76, 18, false, true, true),
  ('STRWHL', 'Steering Wheel', 'Interior/Electronics', null, 'Front', 77, 8, false, true, true),
  ('WINSW', 'Window Switches', 'Interior/Electronics', null, 'Front', 78, 1, false, true, true),
  ('SEATSW', 'Seat Switches', 'Interior/Electronics', null, 'Front', 79, 1, false, true, true),
  ('CNTRCONS', 'Center Console', 'Interior/Electronics', null, 'Front', 80, 12, false, true, true),
  ('CLIMAT', 'Climate Control', 'Interior/Electronics', null, 'Front', 81, 4, false, true, true),
  ('CAMERA', 'Camera', 'Interior/Electronics', null, 'Front', 82, 2, false, true, true),
  ('RADAR', 'Radar Sensor', 'Interior/Electronics', null, 'Front', 83, 2, false, true, true),
  ('STRRACK', 'Steering Rack', 'Suspension/Brakes', null, 'Front', 90, 15, false, true, true),
  ('STRGEAR', 'Steering Gear', 'Suspension/Brakes', null, 'Front', 91, 10, false, true, true),
  ('SPLF', 'Spindle LF', 'Suspension/Brakes', 'LF', 'Front', 92, 8, false, true, true),
  ('SPRF', 'Spindle RF', 'Suspension/Brakes', 'RF', 'Front', 93, 8, false, true, true),
  ('CTRLARM', 'Control Arms', 'Suspension/Brakes', null, 'Front', 94, 10, false, true, true),
  ('STRUT', 'Struts', 'Suspension/Brakes', null, 'Front', 95, 10, false, true, true),
  ('BRKCAL', 'Brake Calipers', 'Suspension/Brakes', null, 'Front', 96, 8, false, true, true),
  ('ABS', 'ABS Module', 'Suspension/Brakes', null, 'Front', 97, 3, false, true, true),
  ('BRKBOOST', 'Brake Booster', 'Suspension/Brakes', null, 'Front', 98, 8, false, true, true),
  ('MASTCYL', 'Master Cylinder', 'Suspension/Brakes', null, 'Front', 99, 6, false, true, true),
  ('CAT', 'Catalytic Converter', 'Other', null, 'Rear', 100, 20, false, true, true),
  ('WHEEL', 'Wheels', 'Other', null, 'Wheel', 101, 25, false, true, true),
  ('SPARE', 'Spare Wheel', 'Other', null, 'Wheel', 102, 25, false, true, true),
  ('JACK', 'Jack Kit', 'Other', null, 'Rear', 103, 10, false, true, true),
  ('BATTTRY', 'Battery Tray', 'Other', null, 'Rear', 104, 4, false, true, true),
  ('FUELPMP', 'Fuel Pump', 'Other', null, 'Rear', 105, 6, false, true, true),
  ('FUELTANK', 'Fuel Tank', 'Other', null, 'Rear', 106, 40, false, true, true),
  ('TRAILBRK', 'Trailer Brake Controller', 'Other', null, 'Front', 107, 3, false, true, true)
ON CONFLICT (part_code) DO NOTHING;
