create table if not exists public.ebay_manual_shipping_costs (
  id bigint generated by default as identity primary key,

  order_id text not null
    references public.ebay_fulfillment_orders(order_id)
    on delete cascade,

  amount numeric(14,2) not null
    check (amount >= 0),

  shipping_type text not null default 'FREIGHT',

  carrier text,
  reference_number text,
  notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ebay_manual_shipping_costs_order_id_idx
  on public.ebay_manual_shipping_costs (order_id);

alter table public.ebay_manual_shipping_costs
  enable row level security;

drop policy if exists "Allow manual shipping cost reads"
  on public.ebay_manual_shipping_costs;

create policy "Allow manual shipping cost reads"
  on public.ebay_manual_shipping_costs
  for select
  to anon, authenticated
  using (true);
