-- Texas OEM Finance V2
-- Permanent bucket allocations for each closed distribution period.
--
-- These rows snapshot the percentage and dollar amount actually
-- allocated at the time the period is closed. Historical periods
-- therefore do not change if allocation percentages change later.

create table if not exists public.finance_distribution_allocations (
  id bigint generated by default as identity primary key,

  distribution_period_id bigint not null
    references public.finance_distribution_periods(id)
    on delete cascade,

  bucket_code text not null,

  bucket_name text not null,

  allocation_percent numeric(7,4) not null
    check (
      allocation_percent >= 0
      and allocation_percent <= 100
    ),

  allocated_amount numeric(14,2) not null
    check (allocated_amount >= 0),

  created_at timestamptz not null default now(),

  unique (distribution_period_id, bucket_code)
);

create index if not exists
  finance_distribution_allocations_period_idx
on public.finance_distribution_allocations (
  distribution_period_id
);

alter table public.finance_distribution_allocations
  enable row level security;

drop policy if exists
  "Allow finance distribution allocation reads"
on public.finance_distribution_allocations;

create policy
  "Allow finance distribution allocation reads"
on public.finance_distribution_allocations
for select
to anon, authenticated
using (true);
