-- Texas OEM Finance V2
-- Permanent distribution snapshots for manually recorded business revenue.
--
-- Manual revenue includes Local Sale, Scrap Shell, Catalytic Converter,
-- Core Sale, and Other Revenue recorded through Revenue Center.
--
-- Each revenue_stream row may participate in ONE Finance distribution only.
-- This prevents local/manual revenue from ever being allocated twice.

create table if not exists public.finance_distribution_manual_revenue (
  id bigint generated by default as identity primary key,

  distribution_period_id bigint not null
    references public.finance_distribution_periods(id)
    on delete restrict,

  revenue_stream_id uuid not null
    references public.revenue_streams(id)
    on delete restrict,

  vehicle_id bigint null,

  source text not null,
  amount numeric(14,2) not null,
  notes text null,
  revenue_created_at timestamptz not null,

  created_at timestamptz not null default now(),

  constraint finance_distribution_manual_revenue_amount_positive
    check (amount > 0),

  constraint finance_distribution_manual_revenue_stream_unique
    unique (revenue_stream_id)
);

create index if not exists
  finance_distribution_manual_revenue_period_idx
on public.finance_distribution_manual_revenue (
  distribution_period_id
);

create index if not exists
  finance_distribution_manual_revenue_created_idx
on public.finance_distribution_manual_revenue (
  revenue_created_at
);

comment on table public.finance_distribution_manual_revenue is
  'Permanent Texas OEM Finance snapshots of manual/local revenue included in closed cash distributions. UNIQUE(revenue_stream_id) prevents double distribution.';

comment on column public.finance_distribution_manual_revenue.revenue_stream_id is
  'Original Revenue Center entry. May appear in only one Finance distribution.';

comment on column public.finance_distribution_manual_revenue.amount is
  'Gross manual business revenue captured at distribution close time.';
