alter table public.ebay_finance_transactions
  drop constraint if exists ebay_finance_transactions_pkey;

alter table public.ebay_finance_transactions
  add column if not exists ledger_id bigint generated by default as identity;

alter table public.ebay_finance_transactions
  add constraint ebay_finance_transactions_pkey
  primary key (ledger_id);

alter table public.ebay_finance_transactions
  alter column transaction_id set not null;

create unique index if not exists ebay_finance_transactions_event_uidx
  on public.ebay_finance_transactions (
    transaction_id,
    transaction_type,
    transaction_date
  );

create index if not exists ebay_finance_transactions_transaction_id_idx
  on public.ebay_finance_transactions (transaction_id);
