-- Texas OEM Finance V2
-- Secure provider connection records.
--
-- One Plaid Item can contain multiple bank accounts.
-- Access tokens are backend-only and never exposed through browser RLS.

create table if not exists public.finance_bank_connections (
  id bigint generated by default as identity primary key,

  provider text not null,
  provider_item_id text not null,

  institution_name text,

  access_token text not null,

  sync_cursor text,

  is_active boolean not null default true,
  last_synced_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique(provider, provider_item_id)
);

alter table public.finance_bank_connections
  enable row level security;

-- Deliberately NO browser policies.
-- Only backend/service-role code may access this table.

revoke all
on public.finance_bank_connections
from anon, authenticated;

comment on table public.finance_bank_connections is
  'Backend-only bank provider connections. Stores Plaid Item access tokens and transaction sync cursors.';
