-- Texas OEM Finance V2
-- Provider-independent business bank transaction ledger.
--
-- Goals:
--   1. Import business bank/card activity automatically.
--   2. Never duplicate the same provider transaction.
--   3. Categorize transactions into Texas OEM cash buckets.
--   4. Allow uncertain transactions to enter a Needs Review queue.
--   5. Preserve raw provider data for reconciliation/debugging.
--   6. Keep this schema independent of Plaid or any single provider.

create table if not exists public.finance_bank_accounts (
  id bigint generated by default as identity primary key,

  provider text not null,
  provider_account_id text not null,

  institution_name text,
  account_name text,
  account_type text,
  account_subtype text,

  mask text,

  current_balance numeric(14,2),
  available_balance numeric(14,2),

  currency_code text not null default 'USD',

  is_active boolean not null default true,

  last_synced_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique(provider, provider_account_id)
);


create table if not exists public.finance_bank_transactions (
  id bigint generated by default as identity primary key,

  bank_account_id bigint not null
    references public.finance_bank_accounts(id)
    on delete cascade,

  provider text not null,
  provider_transaction_id text not null,

  transaction_date date not null,
  authorized_date date,

  merchant_name text,
  description text not null,

  -- Positive = money INTO Texas OEM.
  -- Negative = money OUT of Texas OEM.
  amount numeric(14,2) not null,

  currency_code text not null default 'USD',

  pending boolean not null default false,

  provider_category text,
  provider_subcategory text,

  -- Texas OEM internal cash bucket.
  bucket_code text,

  -- How the bucket was chosen:
  -- AUTO, RULE, MANUAL, or null while unresolved.
  assignment_source text,

  -- 0.0000 through 1.0000.
  assignment_confidence numeric(5,4),

  -- NEW / REVIEW / APPROVED / IGNORED
  review_status text not null default 'NEW',

  notes text,

  -- Full provider payload retained for audit/debugging.
  raw_data jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique(provider, provider_transaction_id),

  constraint finance_bank_transactions_amount_nonzero
    check (amount <> 0),

  constraint finance_bank_transactions_confidence_range
    check (
      assignment_confidence is null
      or (
        assignment_confidence >= 0
        and assignment_confidence <= 1
      )
    ),

  constraint finance_bank_transactions_assignment_source
    check (
      assignment_source is null
      or assignment_source in (
        'AUTO',
        'RULE',
        'MANUAL'
      )
    ),

  constraint finance_bank_transactions_review_status
    check (
      review_status in (
        'NEW',
        'REVIEW',
        'APPROVED',
        'IGNORED'
      )
    )
);


create index if not exists
  finance_bank_transactions_account_date_idx
on public.finance_bank_transactions (
  bank_account_id,
  transaction_date desc
);


create index if not exists
  finance_bank_transactions_review_idx
on public.finance_bank_transactions (
  review_status,
  transaction_date desc
);


create index if not exists
  finance_bank_transactions_bucket_idx
on public.finance_bank_transactions (
  bucket_code,
  transaction_date desc
);


create index if not exists
  finance_bank_transactions_merchant_idx
on public.finance_bank_transactions (
  merchant_name
);


comment on table public.finance_bank_accounts is
  'Provider-independent Texas OEM business bank and card accounts.';


comment on table public.finance_bank_transactions is
  'Imported Texas OEM bank/card transaction ledger used for automatic bucket tracking and reconciliation.';

