-- Texas OEM Finance V2
-- Permanent distribution-period ledger.
--
-- A distribution period represents one closed allocation cycle.
-- Once an eBay order is attached to a period, it cannot be allocated
-- again in another period.

create table if not exists public.finance_distribution_periods (
  id bigint generated by default as identity primary key,

  period_start timestamptz not null,
  period_end timestamptz not null,

  status text not null default 'DRAFT'
    check (status in ('DRAFT', 'CLOSED')),

  gross_revenue numeric(14,2) not null default 0,
  tithe_amount numeric(14,2) not null default 0,

  ebay_fees numeric(14,2) not null default 0,
  seller_shipping numeric(14,2) not null default 0,

  distributable_net numeric(14,2) not null default 0,

  closed_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (period_end >= period_start)
);


create table if not exists public.finance_distribution_orders (
  id bigint generated by default as identity primary key,

  distribution_period_id bigint not null
    references public.finance_distribution_periods(id)
    on delete cascade,

  order_id text not null
    references public.ebay_fulfillment_orders(order_id),

  -- Snapshot the financial truth at allocation time.
  -- This prevents historical distributions from changing later
  -- if eBay data or shipping adjustments change.
  gross_revenue numeric(14,2) not null,

  ebay_fees numeric(14,2) not null,

  ebay_shipping numeric(14,2) not null default 0,

  manual_shipping numeric(14,2) not null default 0,

  seller_shipping numeric(14,2) not null default 0,

  actual_net numeric(14,2) not null,

  created_at timestamptz not null default now(),

  -- Critical safety rule:
  -- one eBay order may only ever belong to ONE distribution period.
  unique (order_id)
);


create index if not exists
  finance_distribution_orders_period_idx
on public.finance_distribution_orders (
  distribution_period_id
);


alter table public.finance_distribution_periods
  enable row level security;

alter table public.finance_distribution_orders
  enable row level security;


drop policy if exists
  "Allow finance distribution period reads"
on public.finance_distribution_periods;

create policy
  "Allow finance distribution period reads"
on public.finance_distribution_periods
for select
to anon, authenticated
using (true);


drop policy if exists
  "Allow finance distribution order reads"
on public.finance_distribution_orders;

create policy
  "Allow finance distribution order reads"
on public.finance_distribution_orders
for select
to anon, authenticated
using (true);
