-- Texas OEM Finance V2
-- Automatic bank transaction categorization rules.
--
-- A rule teaches the OS how a merchant/description should normally
-- be assigned when imported from a bank feed.
--
-- Historical APPROVED transactions are never silently rewritten.

create table if not exists public.finance_transaction_rules (
  id bigint generated by default as identity primary key,

  rule_name text not null,

  -- MERCHANT_CONTAINS or DESCRIPTION_CONTAINS
  match_type text not null,

  match_value text not null,

  bucket_code text not null,

  -- Higher priority rules run first.
  priority integer not null default 100,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint finance_transaction_rules_match_type
    check (
      match_type in (
        'MERCHANT_CONTAINS',
        'DESCRIPTION_CONTAINS'
      )
    ),

  constraint finance_transaction_rules_bucket
    check (
      bucket_code in (
        'DONOR_INVENTORY',
        'OPERATING',
        'BUSINESS_RESERVE',
        'TAX_RESERVE',
        'TOOLS_EQUIPMENT',
        'OWNER_DRAW'
      )
    ),

  unique(match_type, match_value)
);


create index if not exists
  finance_transaction_rules_active_priority_idx
on public.finance_transaction_rules (
  is_active,
  priority desc
);


-- Seed only obvious initial rules.
-- We can add/change these later as Texas OEM's real transaction
-- history teaches us what merchants actually appear as.

insert into public.finance_transaction_rules (
  rule_name,
  match_type,
  match_value,
  bucket_code,
  priority
)
values
  (
    'Copart purchases',
    'MERCHANT_CONTAINS',
    'COPART',
    'DONOR_INVENTORY',
    200
  ),
  (
    'Harbor Freight purchases',
    'MERCHANT_CONTAINS',
    'HARBOR FREIGHT',
    'TOOLS_EQUIPMENT',
    150
  ),
  (
    'FedEx expenses',
    'MERCHANT_CONTAINS',
    'FEDEX',
    'OPERATING',
    150
  ),
  (
    'UPS expenses',
    'MERCHANT_CONTAINS',
    'UPS',
    'OPERATING',
    150
  )
on conflict (match_type, match_value)
do nothing;


comment on table public.finance_transaction_rules is
  'Texas OEM rules used to automatically categorize imported business bank transactions.';

